### ISSUE TITLE
Client doesn't work with runtime

### ISSUE THREAD

**Issue by facekapow** [iefserge/eshttp#6]
I think that eshttp should use the same backend for both node and runtime, since the net module is now fully supported in runtime. It currently throws an error saying that `backend.createClientHandle is not a function`. The full error:

```
TypeError: backend.createClientHandle is not a function
    at new HttpClient (/node_modules/eshttp/lib/http-client.js:16:28)
    at module.exports (/client.js:7:18)
    at runtime.shell.setCommand (/index.js:14:22)
    at Object.exports.runCommand (/node_modules/runtimejs/js/service/shell/index.js:46:21)
    at e (/node_modules/runtime-telnet-server/index.js:40:39)
    at Socket.client.on (/node_modules/runtime-telnet-server/index.js:56:7)
    at Socket.EventEmitter.emit (/node_modules/events/events.js:77:17)
    at readableAddChunk (/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at Socket.Readable.push (/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at Socket._handle.ondata (/node_modules/runtimejs/js/modules/net.js:96:40)
```

**Comment by iefserge** [comment]
@facekapow Using `net` here means using node streams, which, I believe, are slow. I think specialized backend for runtime that uses low level sockets API can be more efficient.
With the addition of whatwg streams to the web platform, I think, current node API is going to be less useful.

**Comment by facekapow** [comment]
OK, that's fine, just that in order for the module to be used for runtime http, it needs to support an http client.

**Comment by iefserge** [comment]
yep, I've been mostly focused on the server component, gotta fix client too.

**Comment by facekapow** [comment]
#7 Fixed this
